[cosmic-ray]
module-path = "test_TrafficSignal.py"
python-version = ""
timeout = 10.0
excluded-modules = []
test-command = "python -m unittest discover tests"

[cosmic-ray.execution-engine]
name = "local"

[cosmic-ray.cloning]
method = "copy"
commands = []
